public enum UIPrefabIds
{
	DisplayNamePopup = 0,
	GenericPopup = 1,
	LoadingProgressBar = 2,
	MainMenu = 3,
	LoadingOverlay = 4,
	SettingsPopup = 5,
	BRMatchHud = 6,
	BRMatchHudTouch = 7,
	BRDeathScreen = 8,
	BRVictoryScreen = 9,
	BRSecondLifeHud = 11,
	BRSecondLifeHudTouch = 12,
	TDMMatchHud = 13,
	TDMMatchHudTouch = 14,
	SurvivalDeathScreen = 16,
	SurvivalMatchHud = 17,
	SurvivalMatchHudTouch = 18,
	DebugLoginPopup = 19,
	UserReportPopup = 20,
	TDMMatchLoadingScreen = 21,
	DamageNumbers = 22,
	CustomizableMainMenuHUD = 23,
	CustomizableMainMenuHUDTouch = 24,
	TDMAARScreen = 25
}
